/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author bijen
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        setBackground(Color.YELLOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        headerLabel1 = new javax.swing.JLabel();
        headerLabel2 = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        emailFooterLabel = new javax.swing.JLabel();
        contactFooterLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        adminChoicePanel = new javax.swing.JPanel();
        adminPhotoLabel = new javax.swing.JLabel();
        logInAsAdminBtn = new javax.swing.JToggleButton();
        logInAsAdminLabel = new javax.swing.JLabel();
        choiceLabel = new javax.swing.JLabel();
        adminChoicePanel1 = new javax.swing.JPanel();
        voterPhotoLabel = new javax.swing.JLabel();
        registerChoiceBtn = new javax.swing.JToggleButton();
        registerChoiceLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(196, 30, 58));
        headerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        headerPanel.setToolTipText("");

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        headerLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        headerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel1.setText("National Voting Registration Portal");

        headerLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        headerLabel2.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel2.setText("Election Commission");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(logoLabel)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(headerLabel1))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(headerLabel2)))
                .addGap(834, 834, 834))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        footerPanel.setBackground(new java.awt.Color(25, 55, 109));
        footerPanel.setLayout(new java.awt.GridLayout());

        emailFooterLabel.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        emailFooterLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailFooterLabel.setText("Email: system@electioncommission.gov");
        footerPanel.add(emailFooterLabel);

        contactFooterLabel.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        contactFooterLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactFooterLabel.setText("CONTACT: +977 01 5553000 ");
        footerPanel.add(contactFooterLabel);

        add(footerPanel, java.awt.BorderLayout.PAGE_END);

        bodyPanel.setBackground(new java.awt.Color(248, 245, 250));
        bodyPanel.setLayout(new java.awt.GridBagLayout());

        adminChoicePanel.setBackground(new java.awt.Color(255, 255, 255));
        adminChoicePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 230), 5));
        adminChoicePanel.setMinimumSize(new java.awt.Dimension(400, 400));

        adminPhotoLabel.setBackground(new java.awt.Color(255, 255, 255));
        adminPhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/admin.png"))); // NOI18N

        logInAsAdminBtn.setBackground(new java.awt.Color(220, 20, 60));
        logInAsAdminBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        logInAsAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        logInAsAdminBtn.setText("Log In As Admin");
        logInAsAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInAsAdminBtnActionPerformed(evt);
            }
        });

        logInAsAdminLabel.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        logInAsAdminLabel.setText("Log In As Admin");

        javax.swing.GroupLayout adminChoicePanelLayout = new javax.swing.GroupLayout(adminChoicePanel);
        adminChoicePanel.setLayout(adminChoicePanelLayout);
        adminChoicePanelLayout.setHorizontalGroup(
            adminChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminChoicePanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(logInAsAdminBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminChoicePanelLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(adminChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logInAsAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminPhotoLabel))
                .addGap(94, 94, 94))
        );
        adminChoicePanelLayout.setVerticalGroup(
            adminChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminChoicePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logInAsAdminLabel)
                .addGap(43, 43, 43)
                .addComponent(adminPhotoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(logInAsAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        bodyPanel.add(adminChoicePanel, gridBagConstraints);

        choiceLabel.setFont(new java.awt.Font("Calisto MT", 3, 48)); // NOI18N
        choiceLabel.setText("Select What You Want To Do");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        bodyPanel.add(choiceLabel, gridBagConstraints);

        adminChoicePanel1.setBackground(new java.awt.Color(255, 255, 255));
        adminChoicePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 230), 5));
        adminChoicePanel1.setMinimumSize(new java.awt.Dimension(400, 400));

        voterPhotoLabel.setBackground(new java.awt.Color(255, 255, 255));
        voterPhotoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bijen\\Downloads\\register.png")); // NOI18N

        registerChoiceBtn.setBackground(new java.awt.Color(220, 20, 60));
        registerChoiceBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        registerChoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerChoiceBtn.setText("Register");
        registerChoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerChoiceBtnActionPerformed(evt);
            }
        });

        registerChoiceLabel.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        registerChoiceLabel.setText("Register As a Voter");

        javax.swing.GroupLayout adminChoicePanel1Layout = new javax.swing.GroupLayout(adminChoicePanel1);
        adminChoicePanel1.setLayout(adminChoicePanel1Layout);
        adminChoicePanel1Layout.setHorizontalGroup(
            adminChoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminChoicePanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(adminChoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerChoiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voterPhotoLabel))
                .addGap(0, 68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminChoicePanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerChoiceBtn)
                .addGap(143, 143, 143))
        );
        adminChoicePanel1Layout.setVerticalGroup(
            adminChoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminChoicePanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(registerChoiceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voterPhotoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerChoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        bodyPanel.add(adminChoicePanel1, gridBagConstraints);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void logInAsAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInAsAdminBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logInAsAdminBtnActionPerformed

    private void registerChoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerChoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerChoiceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminChoicePanel;
    private javax.swing.JPanel adminChoicePanel1;
    private javax.swing.JLabel adminPhotoLabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel choiceLabel;
    private javax.swing.JLabel contactFooterLabel;
    private javax.swing.JLabel emailFooterLabel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel headerLabel1;
    private javax.swing.JLabel headerLabel2;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JToggleButton logInAsAdminBtn;
    private javax.swing.JLabel logInAsAdminLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JToggleButton registerChoiceBtn;
    private javax.swing.JLabel registerChoiceLabel;
    private javax.swing.JLabel voterPhotoLabel;
    // End of variables declaration//GEN-END:variables
}
