/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author bijen
 */

import controller.AdminController;
import controller.CitizenController;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import model.CitizenModel;
import model.CitizenRegistryModel;
import model.AdminRegistryModel;
import controller.AdminController;
import controller.CitizenSorter;

public class MainFrame extends javax.swing.JFrame {
    
    private AdminController adminController;
    private CitizenRegistryModel citizenRegistry;
    private AdminRegistryModel adminRegistry;
    
    /**
     * Display error message to the user.
     * @param message the error message to show.
     */
    public void showError(String message) {
        JOptionPane.showMessageDialog(null, message, "Errror", JOptionPane.ERROR_MESSAGE);
    }
    
    public void updateTable(ArrayList<CitizenModel> citizens) {
        DefaultTableModel model = (DefaultTableModel) OverviewTable.getModel();
        model.setRowCount(0);
        
        for (CitizenModel c : citizens) {
            model.addRow(new Object[]{
                c.getCitizenshipNumber(),
                c.getVoterName(),
                c.getAge(),
                c.getGender(),
                c.getProvince(),
                c.getDistrict(),
                c.getVoteCenter(),
                c.getStatus()
            });
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form Test
     */
    public MainFrame() {
        initComponents();
        
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "home");
        
        //setupNavigation();
        
        //Citizens
        citizenRegistry = new CitizenRegistryModel();
        new CitizenController(citizenRegistry, this);
        
        // Admins
        adminRegistry = new AdminRegistryModel();
        adminController = new AdminController(adminRegistry, citizenRegistry, this);
    }
    
    public void showCard(String cardName) {
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, cardName);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        headerLabel1 = new javax.swing.JLabel();
        headerLabel2 = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerLabel1 = new javax.swing.JLabel();
        footerLabel2 = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        adminChoicePanel = new javax.swing.JPanel();
        adminPhotoLabel = new javax.swing.JLabel();
        chooselogInAsAdminBtn = new javax.swing.JToggleButton();
        logInAsAdminLabel = new javax.swing.JLabel();
        choiceLabel = new javax.swing.JLabel();
        adminChoicePanel1 = new javax.swing.JPanel();
        voterPhotoLabel = new javax.swing.JLabel();
        registerChoiceBtn = new javax.swing.JToggleButton();
        registerChoiceLabel = new javax.swing.JLabel();
        adminLoginPanel = new javax.swing.JPanel();
        AdminLoginLabel = new javax.swing.JLabel();
        AdminField = new javax.swing.JLabel();
        adminIdLabel = new javax.swing.JLabel();
        adminIdField = new javax.swing.JTextField();
        adminPasswordLabel = new javax.swing.JLabel();
        adminPasswordField = new javax.swing.JPasswordField();
        adminLoginBtn = new javax.swing.JButton();
        admindashboardPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OverviewTable = new javax.swing.JTable();
        sortByAgebtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citizen Voting Registration System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1080, 720));

        headerPanel.setBackground(new java.awt.Color(196, 30, 58));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        headerLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        headerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel1.setText("National Voting Registration Portal");

        headerLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        headerLabel2.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel2.setText("Election Commission");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(logoLabel)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(headerLabel1)
                        .addGap(0, 344, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(headerLabel2)
                        .addGap(299, 299, 299))))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(headerLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        footerPanel.setBackground(new java.awt.Color(25, 55, 109));
        footerPanel.setLayout(new java.awt.GridLayout());

        footerLabel1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        footerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        footerLabel1.setText("     Email: system@electioncommission.gov");
        footerPanel.add(footerLabel1);

        footerLabel2.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        footerLabel2.setForeground(new java.awt.Color(255, 255, 255));
        footerLabel2.setText("CONTACT: +977 01 5553000 ");
        footerPanel.add(footerLabel2);

        getContentPane().add(footerPanel, java.awt.BorderLayout.PAGE_END);

        cardPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(248, 245, 250));
        homePanel.setLayout(new java.awt.GridBagLayout());

        adminChoicePanel.setBackground(new java.awt.Color(255, 255, 255));
        adminChoicePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 230), 5));
        adminChoicePanel.setMinimumSize(new java.awt.Dimension(400, 400));

        adminPhotoLabel.setBackground(new java.awt.Color(255, 255, 255));
        adminPhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/admin.png"))); // NOI18N

        chooselogInAsAdminBtn.setBackground(new java.awt.Color(220, 20, 60));
        chooselogInAsAdminBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        chooselogInAsAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        chooselogInAsAdminBtn.setText("Log In As Admin");
        chooselogInAsAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooselogInAsAdminBtnActionPerformed(evt);
            }
        });

        logInAsAdminLabel.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        logInAsAdminLabel.setText("Log In As Admin");

        javax.swing.GroupLayout adminChoicePanelLayout = new javax.swing.GroupLayout(adminChoicePanel);
        adminChoicePanel.setLayout(adminChoicePanelLayout);
        adminChoicePanelLayout.setHorizontalGroup(
            adminChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminChoicePanelLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(adminChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logInAsAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminPhotoLabel))
                .addGap(94, 94, 94))
            .addGroup(adminChoicePanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(chooselogInAsAdminBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminChoicePanelLayout.setVerticalGroup(
            adminChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminChoicePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logInAsAdminLabel)
                .addGap(43, 43, 43)
                .addComponent(adminPhotoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(chooselogInAsAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 0);
        homePanel.add(adminChoicePanel, gridBagConstraints);

        choiceLabel.setFont(new java.awt.Font("Calisto MT", 3, 48)); // NOI18N
        choiceLabel.setText("Select What You Want To Do");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 271, 0, 0);
        homePanel.add(choiceLabel, gridBagConstraints);

        adminChoicePanel1.setBackground(new java.awt.Color(255, 255, 255));
        adminChoicePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 230), 5));
        adminChoicePanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        adminChoicePanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        voterPhotoLabel.setBackground(new java.awt.Color(255, 255, 255));
        voterPhotoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bijen\\Downloads\\register.png")); // NOI18N

        registerChoiceBtn.setBackground(new java.awt.Color(220, 20, 60));
        registerChoiceBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        registerChoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerChoiceBtn.setText("Register");
        registerChoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerChoiceBtnActionPerformed(evt);
            }
        });

        registerChoiceLabel.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        registerChoiceLabel.setText("Register As a Voter");

        javax.swing.GroupLayout adminChoicePanel1Layout = new javax.swing.GroupLayout(adminChoicePanel1);
        adminChoicePanel1.setLayout(adminChoicePanel1Layout);
        adminChoicePanel1Layout.setHorizontalGroup(
            adminChoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminChoicePanel1Layout.createSequentialGroup()
                .addGroup(adminChoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminChoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registerChoiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(adminChoicePanel1Layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(voterPhotoLabel)))
                    .addGroup(adminChoicePanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(registerChoiceBtn)))
                .addGap(68, 68, 68))
        );
        adminChoicePanel1Layout.setVerticalGroup(
            adminChoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminChoicePanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(registerChoiceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voterPhotoLabel)
                .addGap(27, 27, 27)
                .addComponent(registerChoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 184, 30, 47);
        homePanel.add(adminChoicePanel1, gridBagConstraints);

        cardPanel.add(homePanel, "home");

        adminLoginPanel.setBackground(new java.awt.Color(248, 245, 250));
        adminLoginPanel.setLayout(new java.awt.GridBagLayout());

        AdminLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminLoginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/protection.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 101, 34, 0);
        adminLoginPanel.add(AdminLoginLabel, gridBagConstraints);

        AdminField.setFont(new java.awt.Font("DejaVu Serif", 0, 80)); // NOI18N
        AdminField.setText("Admin Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        adminLoginPanel.add(AdminField, gridBagConstraints);

        adminIdLabel.setFont(new java.awt.Font("sansserif", 0, 50)); // NOI18N
        adminIdLabel.setText("Admin ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        adminLoginPanel.add(adminIdLabel, gridBagConstraints);

        adminIdField.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        adminLoginPanel.add(adminIdField, gridBagConstraints);

        adminPasswordLabel.setFont(new java.awt.Font("sansserif", 0, 50)); // NOI18N
        adminPasswordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        adminLoginPanel.add(adminPasswordLabel, gridBagConstraints);

        adminPasswordField.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        adminLoginPanel.add(adminPasswordField, gridBagConstraints);

        adminLoginBtn.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        adminLoginBtn.setText("Log In");
        adminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        adminLoginPanel.add(adminLoginBtn, gridBagConstraints);

        cardPanel.add(adminLoginPanel, "adminLogin");

        OverviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Citizenship Number", "Name", "Age", "Gender", "Province", "District", "Center", "Status"
            }
        ));
        jScrollPane2.setViewportView(OverviewTable);

        sortByAgebtn.setText("Sort By Age");
        sortByAgebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByAgebtnActionPerformed(evt);
            }
        });

        jButton2.setText("Sort By Citizenship Number");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout admindashboardPanelLayout = new javax.swing.GroupLayout(admindashboardPanel);
        admindashboardPanel.setLayout(admindashboardPanelLayout);
        admindashboardPanelLayout.setHorizontalGroup(
            admindashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admindashboardPanelLayout.createSequentialGroup()
                .addGroup(admindashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admindashboardPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(admindashboardPanelLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(sortByAgebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        admindashboardPanelLayout.setVerticalGroup(
            admindashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admindashboardPanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(admindashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(sortByAgebtn))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        cardPanel.add(admindashboardPanel, "adminDashboard");

        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooselogInAsAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooselogInAsAdminBtnActionPerformed
        // TODO add your handling code here:
        // Switches to admin login when clicked
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "adminLogin");
    }//GEN-LAST:event_chooselogInAsAdminBtnActionPerformed

    private void registerChoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerChoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerChoiceBtnActionPerformed

    private void adminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBtnActionPerformed
        // TODO add your handling code here:
        // verifies admin
        
        String adminId = adminIdField.getText().trim();
        String password = new String(adminPasswordField.getPassword());
        
        if (adminId.isEmpty() || password.isEmpty()) {
            showError("Please enter Admin ID and Password");
            return;
        }
        
        boolean success = adminController.login(adminId, password);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Login Successful! Welcome Admin.", "Access Granted", JOptionPane.INFORMATION_MESSAGE);
            showCard("adminDashboard");
        }
    }//GEN-LAST:event_adminLoginBtnActionPerformed

    private void sortByAgebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByAgebtnActionPerformed
        // TODO add your handling code here:
        ArrayList<CitizenModel> citizens = citizenRegistry.getAllCitizens();
        CitizenSorter.sortByAge(citizens);
        updateTable(citizens);
    }//GEN-LAST:event_sortByAgebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList<CitizenModel> citizens = citizenRegistry.getAllCitizens();
        
        CitizenSorter.sortByCitizenshipNumber(citizens);
        updateTable(citizens);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminField;
    private javax.swing.JLabel AdminLoginLabel;
    private javax.swing.JTable OverviewTable;
    private javax.swing.JPanel adminChoicePanel;
    private javax.swing.JPanel adminChoicePanel1;
    private javax.swing.JTextField adminIdField;
    private javax.swing.JLabel adminIdLabel;
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JPanel adminLoginPanel;
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JLabel adminPasswordLabel;
    private javax.swing.JLabel adminPhotoLabel;
    private javax.swing.JPanel admindashboardPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel choiceLabel;
    private javax.swing.JToggleButton chooselogInAsAdminBtn;
    private javax.swing.JLabel footerLabel1;
    private javax.swing.JLabel footerLabel2;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel headerLabel1;
    private javax.swing.JLabel headerLabel2;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logInAsAdminLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JToggleButton registerChoiceBtn;
    private javax.swing.JLabel registerChoiceLabel;
    private javax.swing.JButton sortByAgebtn;
    private javax.swing.JLabel voterPhotoLabel;
    // End of variables declaration//GEN-END:variables
}
