/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.*;

/**
 *
 * @author bijen
 */
public class MainMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMainFrame.class.getName());

    /**
     * Creates new form MainMainFrame
     */
    public MainMainFrame() {
        initComponents();
        
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "loading");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardPanel = new javax.swing.JPanel();
        loadingPanel = new view.BackgroundPanel("/assets/images/BackgroundImage.jpg", view.BackgroundPanel.ScaleMode.FILL);
        quoteLabel = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        authorLabel = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        selectRolePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));

        cardPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        cardPanel.setLayout(new java.awt.CardLayout());

        loadingPanel.setLayout(new java.awt.GridBagLayout());

        quoteLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 50)); // NOI18N
        quoteLabel.setText("Be The Nation's Voice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        loadingPanel.add(quoteLabel, gridBagConstraints);

        loadingBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        loadingBar.setMinimumSize(new java.awt.Dimension(200, 10));
        loadingBar.setName(""); // NOI18N
        loadingBar.setPreferredSize(new java.awt.Dimension(200, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        loadingPanel.add(loadingBar, gridBagConstraints);

        authorLabel.setFont(new java.awt.Font("Viner Hand ITC", 2, 48)); // NOI18N
        authorLabel.setText("- Saral Registry");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        loadingPanel.add(authorLabel, gridBagConstraints);

        loadingLabel.setText("Loading...........");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        loadingPanel.add(loadingLabel, gridBagConstraints);

        loadingValue.setText("0%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        loadingPanel.add(loadingValue, gridBagConstraints);

        cardPanel.add(loadingPanel, "loading");

        javax.swing.GroupLayout selectRolePanelLayout = new javax.swing.GroupLayout(selectRolePanel);
        selectRolePanel.setLayout(selectRolePanelLayout);
        selectRolePanelLayout.setHorizontalGroup(
            selectRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        selectRolePanelLayout.setVerticalGroup(
            selectRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        cardPanel.add(selectRolePanel, "selectRole");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        MainMainFrame mmf = new MainMainFrame();
        mmf.setVisible(true);
        
        // Start loading in background thread
        new Thread(() -> {
            try {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(50); // Adjust speed here (lower = faster)
                    
                    final int progress = i;
                    String message;
                    
                    if (i < 20) {
                        message = "Loading Modules...";
                    } else if (i < 50) {
                        message = "Initializing System...";
                    } else if (i < 80) {
                        message = "Preparing Interface...";
                    } else {
                        message = "Almost Ready...";
                    }
                    
                    final String finalMessage = message;
                    
                    // Update UI
                    java.awt.EventQueue.invokeLater(() -> {
                        mmf.loadingBar.setValue(progress);
                        mmf.loadingValue.setText(finalMessage + " " + progress + "%");
                    });
                }
                
                // Switch to main panel after loading
                java.awt.EventQueue.invokeLater(() -> {
                    mmf.showMainContent();
                });
                
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    });
}
    
    public void showMainContent() {
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "selectRole");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingLabel;
    private view.BackgroundPanel loadingPanel;
    private javax.swing.JLabel loadingValue;
    private javax.swing.JLabel quoteLabel;
    private javax.swing.JPanel selectRolePanel;
    // End of variables declaration//GEN-END:variables
}
