/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.*;
import javax.swing.*;
import controller.AdminController;
import model.AdminModel;
import model.AdminRegistryModel;
import model.CitizenRegistryModel;

/**
 *
 * @author bijen
 */
public class MainMainFrame extends javax.swing.JFrame {
    
    private AdminController adminController;
    private AdminRegistryModel adminRegistry;
    private CitizenRegistryModel citizenRegistry;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMainFrame.class.getName());

    /**
     * Creates new form MainMainFrame
     */
    public MainMainFrame() {
        initComponents();
        
        adminRegistry = new AdminRegistryModel();
        citizenRegistry = new CitizenRegistryModel();
        
        adminController = new AdminController(adminRegistry, citizenRegistry, null);
        
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "loading");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchOptionGroup = new javax.swing.ButtonGroup();
        cardPanel = new javax.swing.JPanel();
        loadingPanel = new view.BackgroundPanel("/assets/images/BackgroundImage.jpg", view.BackgroundPanel.ScaleMode.FILL);
        quoteLabel = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        authorLabel = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        logoPanel = new view.BackgroundPanel("/assets/images/Logo.png", view.BackgroundPanel.ScaleMode.FILL);
        headerContainer = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        subHeaderLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerLabel1 = new javax.swing.JLabel();
        footerLabel2 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        selectRolePanel = new javax.swing.JPanel();
        selectRoleLabel = new javax.swing.JLabel();
        adminImg = new view.BackgroundPanel("/assets/images/admin.png", view.BackgroundPanel.ScaleMode.FILL);
        citizenImg = new view.BackgroundPanel("/assets/images/register.png", view.BackgroundPanel.ScaleMode.FILL);
        adminChoiceBtn = new javax.swing.JButton();
        citizenChoiceBtn = new javax.swing.JButton();
        adminLoginPanel = new javax.swing.JPanel();
        protectionImg = new view.BackgroundPanel("/assets/images/protection.png", view.BackgroundPanel.ScaleMode.FILL);
        adminIdLabel = new javax.swing.JLabel();
        adminIdField = new javax.swing.JTextField();
        adminPasswordLabel = new javax.swing.JLabel();
        adminPasswordField = new javax.swing.JPasswordField();
        adminLoginLabel = new javax.swing.JLabel();
        forgetBtn = new javax.swing.JButton();
        logInBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        adminDashboardPanel = new javax.swing.JPanel();
        adminHeaderPanel = new javax.swing.JPanel();
        adminheaderLeft = new javax.swing.JPanel();
        welcomeAdmin = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        adminHeaderCenter = new javax.swing.JPanel();
        carouselLabel = new javax.swing.JLabel();
        adminDashboardPane = new javax.swing.JTabbedPane();
        dashboardPane = new javax.swing.JPanel();
        statsLabel = new javax.swing.JLabel();
        dashboardFooterPanel = new javax.swing.JPanel();
        searchManageBtn = new javax.swing.JButton();
        dashboardCenterPanel = new javax.swing.JPanel();
        dashboardPanel1 = new javax.swing.JPanel();
        dashboardPanel2 = new javax.swing.JPanel();
        dashboardPanel3 = new javax.swing.JPanel();
        dashboardPanel4 = new javax.swing.JPanel();
        dashboardPanel5 = new javax.swing.JPanel();
        dashboardPanel6 = new javax.swing.JPanel();
        adminManagePane = new javax.swing.JPanel();
        manageCitizenLabel = new javax.swing.JLabel();
        manageCitizenFooterPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();
        refreshManageBtn = new javax.swing.JButton();
        citizenRecordPane = new javax.swing.JScrollPane();
        citizensTable = new javax.swing.JTable();
        SearchPane = new javax.swing.JPanel();
        searchHeader = new javax.swing.JPanel();
        citizenshipNoBtn = new javax.swing.JRadioButton();
        nameBtn = new javax.swing.JRadioButton();
        phoneNumberBtn = new javax.swing.JRadioButton();
        searchField = new javax.swing.JTextField();
        linearSearchBtn = new javax.swing.JButton();
        binarySearchBtn = new javax.swing.JButton();
        searchScrollPane = new javax.swing.JScrollPane();
        detailsTextarea = new javax.swing.JTextArea();
        sortPane = new javax.swing.JPanel();
        sortHeader = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saral Registry");
        setPreferredSize(new java.awt.Dimension(900, 700));

        cardPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        cardPanel.setLayout(new java.awt.CardLayout());

        loadingPanel.setLayout(new java.awt.GridBagLayout());

        quoteLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 50)); // NOI18N
        quoteLabel.setText("Be The Nation's Voice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        loadingPanel.add(quoteLabel, gridBagConstraints);

        loadingBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        loadingBar.setMinimumSize(new java.awt.Dimension(200, 10));
        loadingBar.setName(""); // NOI18N
        loadingBar.setPreferredSize(new java.awt.Dimension(200, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        loadingPanel.add(loadingBar, gridBagConstraints);

        authorLabel.setFont(new java.awt.Font("Viner Hand ITC", 2, 48)); // NOI18N
        authorLabel.setText("- Saral Registry");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        loadingPanel.add(authorLabel, gridBagConstraints);

        loadingLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        loadingLabel.setText("Loading...........");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        loadingPanel.add(loadingLabel, gridBagConstraints);

        loadingValue.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        loadingValue.setText("0%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        loadingPanel.add(loadingValue, gridBagConstraints);

        cardPanel.add(loadingPanel, "loading");

        mainContentPanel.setMinimumSize(new java.awt.Dimension(900, 500));
        mainContentPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(220, 20, 20));
        headerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        headerPanel.add(logoPanel);

        headerContainer.setBackground(new java.awt.Color(220, 20, 20));
        headerContainer.setLayout(new java.awt.GridBagLayout());

        headerLabel.setBackground(new java.awt.Color(220, 20, 20));
        headerLabel.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("National Voter Registration Portal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        headerContainer.add(headerLabel, gridBagConstraints);

        subHeaderLabel.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        subHeaderLabel.setForeground(new java.awt.Color(255, 255, 255));
        subHeaderLabel.setText("Election Commission");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        headerContainer.add(subHeaderLabel, gridBagConstraints);

        headerPanel.add(headerContainer);

        mainContentPanel.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        footerPanel.setBackground(new java.awt.Color(0, 56, 147));
        footerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        footerPanel.setLayout(new java.awt.GridBagLayout());

        footerLabel1.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        footerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        footerLabel1.setText("Email: system@electioncommission.gov");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        footerPanel.add(footerLabel1, gridBagConstraints);

        footerLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        footerLabel2.setForeground(new java.awt.Color(255, 255, 255));
        footerLabel2.setText("Contact: +977 01 5553000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        footerPanel.add(footerLabel2, gridBagConstraints);

        mainContentPanel.add(footerPanel, java.awt.BorderLayout.PAGE_END);

        contentPanel.setLayout(new java.awt.CardLayout());

        selectRolePanel.setBackground(new java.awt.Color(255, 255, 255));
        selectRolePanel.setPreferredSize(new java.awt.Dimension(900, 500));
        selectRolePanel.setLayout(new java.awt.GridBagLayout());

        selectRoleLabel.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        selectRoleLabel.setText("Select Your Role");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        selectRolePanel.add(selectRoleLabel, gridBagConstraints);

        adminImg.setBackground(new java.awt.Color(255, 255, 255));
        adminImg.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        adminImg.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout adminImgLayout = new javax.swing.GroupLayout(adminImg);
        adminImg.setLayout(adminImgLayout);
        adminImgLayout.setHorizontalGroup(
            adminImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        adminImgLayout.setVerticalGroup(
            adminImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        selectRolePanel.add(adminImg, gridBagConstraints);

        citizenImg.setBackground(new java.awt.Color(255, 255, 255));
        citizenImg.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        citizenImg.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout citizenImgLayout = new javax.swing.GroupLayout(citizenImg);
        citizenImg.setLayout(citizenImgLayout);
        citizenImgLayout.setHorizontalGroup(
            citizenImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        citizenImgLayout.setVerticalGroup(
            citizenImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        selectRolePanel.add(citizenImg, gridBagConstraints);

        adminChoiceBtn.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        adminChoiceBtn.setText("Admin ");
        adminChoiceBtn.setName(""); // NOI18N
        adminChoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminChoiceBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        selectRolePanel.add(adminChoiceBtn, gridBagConstraints);

        citizenChoiceBtn.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        citizenChoiceBtn.setText("Citizen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        selectRolePanel.add(citizenChoiceBtn, gridBagConstraints);

        contentPanel.add(selectRolePanel, "selectRole");

        adminLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminLoginPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        adminLoginPanel.setLayout(new java.awt.GridBagLayout());

        protectionImg.setBackground(new java.awt.Color(255, 255, 255));
        protectionImg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        protectionImg.setPreferredSize(new java.awt.Dimension(250, 200));

        javax.swing.GroupLayout protectionImgLayout = new javax.swing.GroupLayout(protectionImg);
        protectionImg.setLayout(protectionImgLayout);
        protectionImgLayout.setHorizontalGroup(
            protectionImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        protectionImgLayout.setVerticalGroup(
            protectionImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 64);
        adminLoginPanel.add(protectionImg, gridBagConstraints);

        adminIdLabel.setFont(new java.awt.Font("Thames", 0, 36)); // NOI18N
        adminIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminIdLabel.setText("Admin Id");
        adminIdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        adminLoginPanel.add(adminIdLabel, gridBagConstraints);

        adminIdField.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        adminLoginPanel.add(adminIdField, gridBagConstraints);

        adminPasswordLabel.setFont(new java.awt.Font("Thames", 0, 36)); // NOI18N
        adminPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPasswordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        adminLoginPanel.add(adminPasswordLabel, gridBagConstraints);

        adminPasswordField.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        adminLoginPanel.add(adminPasswordField, gridBagConstraints);

        adminLoginLabel.setFont(new java.awt.Font("Thames", 1, 100)); // NOI18N
        adminLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLoginLabel.setText("Admin Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        adminLoginPanel.add(adminLoginLabel, gridBagConstraints);

        forgetBtn.setBackground(new java.awt.Color(242, 242, 242));
        forgetBtn.setText("Forget Password? Click Here");
        forgetBtn.setBorder(null);
        forgetBtn.setBorderPainted(false);
        forgetBtn.setContentAreaFilled(false);
        forgetBtn.setPreferredSize(new java.awt.Dimension(165, 30));
        forgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        adminLoginPanel.add(forgetBtn, gridBagConstraints);

        logInBtn.setText("Log In");
        logInBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        adminLoginPanel.add(logInBtn, gridBagConstraints);

        backBtn.setText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        adminLoginPanel.add(backBtn, gridBagConstraints);

        contentPanel.add(adminLoginPanel, "adminLogin");

        adminDashboardPanel.setLayout(new java.awt.BorderLayout());

        adminHeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminHeaderPanel.setPreferredSize(new java.awt.Dimension(0, 120));
        adminHeaderPanel.setLayout(new java.awt.BorderLayout());

        adminheaderLeft.setBackground(new java.awt.Color(255, 255, 255));

        welcomeAdmin.setFont(new java.awt.Font("SimSun", 1, 28)); // NOI18N
        welcomeAdmin.setText("Welcome, Admin!");
        adminheaderLeft.add(welcomeAdmin);

        adminHeaderPanel.add(adminheaderLeft, java.awt.BorderLayout.LINE_START);

        exitPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        logoutBtn.setText("Logout");
        logoutBtn.setPreferredSize(new java.awt.Dimension(72, 30));
        exitPanel.add(logoutBtn);

        adminHeaderPanel.add(exitPanel, java.awt.BorderLayout.LINE_END);

        adminHeaderCenter.setBackground(new java.awt.Color(255, 255, 255));
        adminHeaderCenter.setLayout(new java.awt.GridBagLayout());

        carouselLabel.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        carouselLabel.setText("Loading.......");
        adminHeaderCenter.add(carouselLabel, new java.awt.GridBagConstraints());

        adminHeaderPanel.add(adminHeaderCenter, java.awt.BorderLayout.CENTER);

        adminDashboardPanel.add(adminHeaderPanel, java.awt.BorderLayout.PAGE_START);

        adminDashboardPane.setBackground(new java.awt.Color(255, 255, 255));

        dashboardPane.setLayout(new java.awt.BorderLayout());

        statsLabel.setBackground(new java.awt.Color(255, 255, 255));
        statsLabel.setFont(new java.awt.Font("SimSun", 1, 28)); // NOI18N
        statsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statsLabel.setText("Statistics Overview");
        dashboardPane.add(statsLabel, java.awt.BorderLayout.PAGE_START);

        dashboardFooterPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardFooterPanel.setLayout(new java.awt.GridBagLayout());

        searchManageBtn.setText("Refresh");
        searchManageBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        dashboardFooterPanel.add(searchManageBtn, new java.awt.GridBagConstraints());

        dashboardPane.add(dashboardFooterPanel, java.awt.BorderLayout.PAGE_END);

        dashboardCenterPanel.setLayout(new java.awt.GridLayout(2, 3, 15, 15));

        dashboardPanel1.setLayout(new java.awt.BorderLayout());
        dashboardCenterPanel.add(dashboardPanel1);

        dashboardPanel2.setLayout(new java.awt.BorderLayout());
        dashboardCenterPanel.add(dashboardPanel2);

        dashboardPanel3.setLayout(new java.awt.BorderLayout());
        dashboardCenterPanel.add(dashboardPanel3);

        dashboardPanel4.setLayout(new java.awt.BorderLayout());
        dashboardCenterPanel.add(dashboardPanel4);

        dashboardPanel5.setLayout(new java.awt.BorderLayout());
        dashboardCenterPanel.add(dashboardPanel5);

        dashboardPanel6.setLayout(new java.awt.BorderLayout());
        dashboardCenterPanel.add(dashboardPanel6);

        dashboardPane.add(dashboardCenterPanel, java.awt.BorderLayout.CENTER);

        adminDashboardPane.addTab("Dashboard", dashboardPane);

        adminManagePane.setLayout(new java.awt.BorderLayout());

        manageCitizenLabel.setBackground(new java.awt.Color(255, 255, 255));
        manageCitizenLabel.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        manageCitizenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageCitizenLabel.setText("Manage Citizen Records");
        adminManagePane.add(manageCitizenLabel, java.awt.BorderLayout.PAGE_START);

        manageCitizenFooterPanel.setLayout(new java.awt.GridLayout());

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        manageCitizenFooterPanel.add(addBtn);

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        manageCitizenFooterPanel.add(viewBtn);

        editBtn.setText("Edit");
        manageCitizenFooterPanel.add(editBtn);

        deleteBtn.setText("Delete");
        manageCitizenFooterPanel.add(deleteBtn);

        approveBtn.setText("Approve");
        manageCitizenFooterPanel.add(approveBtn);

        rejectBtn.setText("Reject");
        manageCitizenFooterPanel.add(rejectBtn);

        refreshManageBtn.setText("Refresh");
        manageCitizenFooterPanel.add(refreshManageBtn);

        adminManagePane.add(manageCitizenFooterPanel, java.awt.BorderLayout.PAGE_END);

        citizensTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Citizenship No", "Full Name", "Age", "Phone", "Province", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        citizenRecordPane.setViewportView(citizensTable);

        adminManagePane.add(citizenRecordPane, java.awt.BorderLayout.CENTER);

        adminDashboardPane.addTab("Manage Citizens", adminManagePane);

        SearchPane.setLayout(new java.awt.BorderLayout());

        searchHeader.setLayout(new java.awt.GridBagLayout());

        searchOptionGroup.add(citizenshipNoBtn);
        citizenshipNoBtn.setText("Citizenship Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        searchHeader.add(citizenshipNoBtn, gridBagConstraints);

        searchOptionGroup.add(nameBtn);
        nameBtn.setText("Voter Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        searchHeader.add(nameBtn, gridBagConstraints);

        searchOptionGroup.add(phoneNumberBtn);
        phoneNumberBtn.setText("Phone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        searchHeader.add(phoneNumberBtn, gridBagConstraints);

        searchField.setToolTipText("Enter Details");
        searchField.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        searchHeader.add(searchField, gridBagConstraints);

        linearSearchBtn.setText("Linear Search");
        linearSearchBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        searchHeader.add(linearSearchBtn, gridBagConstraints);

        binarySearchBtn.setText("Binary Search");
        binarySearchBtn.setPreferredSize(new java.awt.Dimension(101, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        searchHeader.add(binarySearchBtn, gridBagConstraints);

        SearchPane.add(searchHeader, java.awt.BorderLayout.PAGE_START);

        detailsTextarea.setColumns(20);
        detailsTextarea.setRows(5);
        searchScrollPane.setViewportView(detailsTextarea);

        SearchPane.add(searchScrollPane, java.awt.BorderLayout.CENTER);

        adminDashboardPane.addTab("Search", SearchPane);

        sortPane.setLayout(new java.awt.BorderLayout());

        jRadioButton1.setText("Citizenship Number");
        sortHeader.add(jRadioButton1);

        jRadioButton2.setText("Name");
        sortHeader.add(jRadioButton2);

        jRadioButton3.setText("Age");
        sortHeader.add(jRadioButton3);

        jRadioButton4.setText("Ascending");
        sortHeader.add(jRadioButton4);

        jRadioButton5.setText("Descending");
        sortHeader.add(jRadioButton5);

        jButton1.setText("Sort ");
        sortHeader.add(jButton1);

        jButton2.setText("Reset");
        sortHeader.add(jButton2);

        sortPane.add(sortHeader, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        sortPane.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        sortPane.add(jPanel3, java.awt.BorderLayout.CENTER);

        adminDashboardPane.addTab("Sort", sortPane);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        adminDashboardPane.addTab("Queue", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        adminDashboardPane.addTab("History", jPanel7);

        adminDashboardPanel.add(adminDashboardPane, java.awt.BorderLayout.CENTER);

        contentPanel.add(adminDashboardPanel, "adminDashboard");

        mainContentPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        cardPanel.add(mainContentPanel, "mainContent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminChoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminChoiceBtnActionPerformed
        // TODO add your handling code here:
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "adminLogin");     
    }//GEN-LAST:event_adminChoiceBtnActionPerformed

    private void forgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetBtnActionPerformed
        // TODO add your handling code here:
        forgetBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        forgetBtn.setForeground(new Color(0, 102, 204));
        
        try {
           String adminId = JOptionPane.showInputDialog(this, "Enter your Admin ID: ", "Password Reset - Verify Identity", JOptionPane.QUESTION_MESSAGE);
           
           if (adminId == null) {
               return;
           }
           
           if (adminId.trim().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Admin ID cannot be empty.", "Input Required", JOptionPane.WARNING_MESSAGE);
               return;
           }
           
           if (!adminRegistry.adminExists(adminId.trim())) {
               JOptionPane.showMessageDialog(this, "Admin ID not Found. \nPlease check your Admin ID and try again.", "Admin Not Found", JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           JPasswordField newPasswordField = new JPasswordField(20);
           Object[] message1 = {"Enter your new password:", "(Must be at least 8 characters)", newPasswordField};
           
           int option1 = JOptionPane.showConfirmDialog(this, message1, "Password Reset - New Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
           
           if (option1 != JOptionPane.OK_OPTION) {
               return;
           }
           
           String newPassword = new String(newPasswordField.getPassword());
           
           if (newPassword.trim().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Password cannot b empty.", "Input Required", JOptionPane.WARNING_MESSAGE);
               return;
           }
           
           if (newPassword.trim().length() < 8) {
               JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long.", "Password too short", JOptionPane.WARNING_MESSAGE);
               return;
           }
           
           JPasswordField confirmPasswordField = new JPasswordField(20);
           Object[] message2 = {"Confirm your nw password:", confirmPasswordField};
           
           int option2 = JOptionPane.showConfirmDialog(this, message2, "Password Reset - Confirm Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
           
           if (option2 != JOptionPane.OK_OPTION) {
               return;
            }
           String confirmPassword = new String(confirmPasswordField.getPassword());
           
           if (!newPassword.equals(confirmPassword)) {
               JOptionPane.showMessageDialog(this, "Passwords do not match.", "Password Mismatch", JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           boolean removed = adminRegistry.removeAdmin(adminId.trim());
           
           if (!removed) {
               JOptionPane.showMessageDialog(this, "Failed to reset password.", "Reset Failed", JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           AdminModel newAdmin = new AdminModel(adminId.trim(), newPassword.trim());
           adminRegistry.addAdmin(newAdmin);
           
           JOptionPane.showMessageDialog(this, "Password reset successful", "Success", JOptionPane.INFORMATION_MESSAGE);
       } catch (IllegalArgumentException e) {
           JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Reset Failed", JOptionPane.ERROR_MESSAGE);
       } catch (NullPointerException e) {
           JOptionPane.showMessageDialog(this, "System Error: Admin Registry not initialized", "System Error", JOptionPane.ERROR_MESSAGE);
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "An unexpected error occured. \nPlease try again.", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_forgetBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "selectRole");
    }//GEN-LAST:event_backBtnActionPerformed

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        // TODO add your handling code here:
        try {
            String adminId = adminIdField.getText().trim();
            String password = new String(adminPasswordField.getPassword()).trim();
            
            if (!validateLoginInput(adminId, password)) {
                return;
            }
            
            boolean loginSuccess = adminController.login(adminId, password);
            
            if (loginSuccess) {
                JOptionPane.showMessageDialog(this, "Login Successful! Welcome, " + adminId.trim(), "Success", JOptionPane.INFORMATION_MESSAGE);
                
                try {
                    if (adminIdField != null) {
                        adminIdField.setText("");
                    }
                    if (adminPasswordField != null) {
                        adminPasswordField.setText("");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                CardLayout cl = (CardLayout) contentPanel.getLayout();
                cl.show(contentPanel, "adminDashboard");
                
            }else {
                JOptionPane.showMessageDialog(this, "Invalid Admin ID or Password. \nPlease try again.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                
                adminPasswordField.setText("");
                adminPasswordField.requestFocus();
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "System error: Missing required components. \nPlease restart the application.", "System Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage(), "Validation Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_logInBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBtnActionPerformed

    /**
     * 
     */
    private boolean validateLoginInput(String adminId, String password) {
        if (adminId == null || password == null) {
            JOptionPane.showMessageDialog(this, "Please enter ID and Password", "System Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        String trimmedId = adminId.trim();
        String trimmedPassword = password.trim();
        
        if (trimmedId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Admin ID cannot be empty. \nPlease enter your Admin ID.", "Input Required.", JOptionPane.WARNING_MESSAGE);
            adminIdField.requestFocus();
            return false;
        }
        
        if (trimmedPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty. \nPlease enter your password.", "Input Required.", JOptionPane.WARNING_MESSAGE);
            adminPasswordField.requestFocus();
            return false;
        }
        if (adminId.trim().isEmpty() || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your crdentials.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Information", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MainMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        MainMainFrame mmf = new MainMainFrame();
        mmf.setVisible(true);
        
        // Start loading in background thread
        new Thread(() -> {
            try {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(20); // Adjust speed here (lower = faster)
                    
                    final int progress = i;
                    String message;
                    
                    if (i < 20) {
                        message = "Loading Modules...";
                    } else if (i < 50) {
                        message = "Initializing System...";
                    } else if (i < 80) {
                        message = "Preparing Interface...";
                    } else {
                        message = "Almost Ready...";
                    }
                    
                    final String finalMessage = message;
                    
                    // Update UI
                    java.awt.EventQueue.invokeLater(() -> {
                        mmf.loadingBar.setValue(progress);
                        mmf.loadingValue.setText(finalMessage + " " + progress + "%");
                    });
                }
                
                // Switch to main panel after loading
                java.awt.EventQueue.invokeLater(() -> {
                    mmf.showMainContent();
                });
                
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    });
}
    
    public void showMainContent() {
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "mainContent");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SearchPane;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton adminChoiceBtn;
    private javax.swing.JTabbedPane adminDashboardPane;
    private javax.swing.JPanel adminDashboardPanel;
    private javax.swing.JPanel adminHeaderCenter;
    private javax.swing.JPanel adminHeaderPanel;
    private javax.swing.JTextField adminIdField;
    private javax.swing.JLabel adminIdLabel;
    private view.BackgroundPanel adminImg;
    private javax.swing.JLabel adminLoginLabel;
    private javax.swing.JPanel adminLoginPanel;
    private javax.swing.JPanel adminManagePane;
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JLabel adminPasswordLabel;
    private javax.swing.JPanel adminheaderLeft;
    private javax.swing.JButton approveBtn;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton binarySearchBtn;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel carouselLabel;
    private javax.swing.JButton citizenChoiceBtn;
    private view.BackgroundPanel citizenImg;
    private javax.swing.JScrollPane citizenRecordPane;
    private javax.swing.JTable citizensTable;
    private javax.swing.JRadioButton citizenshipNoBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel dashboardCenterPanel;
    private javax.swing.JPanel dashboardFooterPanel;
    private javax.swing.JPanel dashboardPane;
    private javax.swing.JPanel dashboardPanel1;
    private javax.swing.JPanel dashboardPanel2;
    private javax.swing.JPanel dashboardPanel3;
    private javax.swing.JPanel dashboardPanel4;
    private javax.swing.JPanel dashboardPanel5;
    private javax.swing.JPanel dashboardPanel6;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea detailsTextarea;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel footerLabel1;
    private javax.swing.JLabel footerLabel2;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JButton forgetBtn;
    private javax.swing.JPanel headerContainer;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JButton linearSearchBtn;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingLabel;
    private view.BackgroundPanel loadingPanel;
    private javax.swing.JLabel loadingValue;
    private javax.swing.JButton logInBtn;
    private view.BackgroundPanel logoPanel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel manageCitizenFooterPanel;
    private javax.swing.JLabel manageCitizenLabel;
    private javax.swing.JRadioButton nameBtn;
    private javax.swing.JRadioButton phoneNumberBtn;
    private view.BackgroundPanel protectionImg;
    private javax.swing.JLabel quoteLabel;
    private javax.swing.JButton refreshManageBtn;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchHeader;
    private javax.swing.JButton searchManageBtn;
    private javax.swing.ButtonGroup searchOptionGroup;
    private javax.swing.JScrollPane searchScrollPane;
    private javax.swing.JLabel selectRoleLabel;
    private javax.swing.JPanel selectRolePanel;
    private javax.swing.JPanel sortHeader;
    private javax.swing.JPanel sortPane;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JLabel subHeaderLabel;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel welcomeAdmin;
    // End of variables declaration//GEN-END:variables
}
