/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author bijen
 */

import controller.AdminController;
import controller.CitizenController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import model.CitizenModel;
import model.CitizenRegistryModel;
import model.AdminRegistryModel;

public class WelcomePanelView extends javax.swing.JFrame {
    
    /**
     * Display error message to the user.
     * @param message the error message to show.
     */
    public void showError(String message) {
        JOptionPane.showMessageDialog(null, message, "Errror", JOptionPane.ERROR_MESSAGE);
    }
    
    public void updateTable(ArrayList<CitizenModel> citizens) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (CitizenModel c : citizens) {
            model.addRow(new Object[]{
                c.getCitizenshipNumber(),
                c.getVoterName(),
                c.getAge(),
                c.getDistrict(),
                c.getVoteCenter()
            });
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WelcomePanelView.class.getName());

    /**
     * Creates new form Test
     */
    public WelcomePanelView() {
        initComponents();
        
        // Citizens
        CitizenRegistryModel registry = new CitizenRegistryModel();
        new CitizenController(registry, this);
        
        // Admins
        AdminRegistryModel adminRegistry = new AdminRegistryModel();
        AdminController adminController = new AdminController(adminRegistry, registry, this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1193, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WelcomePanelView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
